# -*- coding: utf-8 -*-
"""Another copy of data jalan

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vz2EVBOaUnqekvWN2NOEvPhRTDG4h6Or
"""

!pip install osmnx

import osmnx as ox
import matplotlib.pyplot as plt

# Specify the coordinates (latitude, longitude) of Universitas Gadjah Mada
latitude = -7.770717
longitude = 110.377724
point = (latitude, longitude)

# Define the distance (in meters) for the bounding box around the point
distance = 1000  # Adjust the distance as needed

# Fetch the street network data for the specified location
graph = ox.graph_from_point(point, dist=distance, network_type='all')

# Plot the graph
fig, ax = ox.plot_graph(graph)
plt.show()

import osmnx as ox
import matplotlib.pyplot as plt
import random
from datetime import datetime, timedelta

# Convert the graph to GeoDataFrames
nodes, edges = ox.graph_to_gdfs(graph)

# Randomly select nodes for potential stations and assign charging slots
num_stations = 10  # Number of stations
potential_station_nodes = random.sample(list(nodes.index), num_stations)
charging_slots = {node: random.choice([3, 5]) for node in potential_station_nodes}

# Define a maximum time range for the trips (Tmax)
Tmax = timedelta(hours=1)  # Adjust as needed

# Function to calculate travel time in minutes
def calculate_travel_time(distance_meters, speed_kmh):
    speed_m_per_s = speed_kmh * 1000 / 3600  # Convert speed to m/s
    travel_time_seconds = distance_meters / speed_m_per_s
    return timedelta(seconds=travel_time_seconds)

num_trips = 40
trip_pairs = []

start_time_range = datetime.now()

for _ in range(num_trips):
    station1, station2 = random.sample(potential_station_nodes, 2)
    start_time = start_time_range + timedelta(minutes=random.randint(0, int(Tmax.total_seconds() / 60) - 1))

    route = ox.shortest_path(graph, station1, station2)

    # Check if a route exists
    if route is not None:
        route_length_meters = sum(ox.utils_graph.get_route_edge_attributes(graph, route, 'length'))
        travel_duration = calculate_travel_time(route_length_meters, average_speed_kmh)

        # Ensure end time does not exceed Tmax
        end_time = min(start_time + travel_duration, start_time_range + Tmax)

        trip_pairs.append((station1, station2, start_time, end_time))
    else:
        print(f"No path found between {station1} and {station2}")

# Plot the street network
fig, ax = ox.plot_graph(graph, show=False, close=False)

# Plot potential stations with charging slots
for node in potential_station_nodes:
    x, y = nodes.loc[node, 'x'], nodes.loc[node, 'y']
    slots = charging_slots[node]
    ax.scatter(x, y, c='red', s=100, zorder=3)
    ax.text(x, y, f'{slots} slots', horizontalalignment='center', verticalalignment='center')

# Plot trips and print trip details
for i, (origin_node, destination_node, start_time, end_time) in enumerate(trip_pairs):
    route = ox.shortest_path(graph, origin_node, destination_node)

    # Ensure route exists
    if route:
        route_length_meters = sum(ox.utils_graph.get_route_edge_attributes(graph, route, 'length'))
        route_length_km = route_length_meters / 1000  # Convert to kilometers
        battery_consumption = battery_consumption_rate * route_length_km  # Battery consumption in kWh

        travel_duration = calculate_travel_time(route_length_meters, average_speed_kmh)
        travel_time_minutes = travel_duration.total_seconds() / 60
        trip_profit = profit_per_minute * travel_time_minutes  # Profit in IDR

        print(f"Trip {i+1}: Battery Consumption: {battery_consumption:.2f} kWh, Profit Contribution: IDR {trip_profit:.2f}")

# Display the plot
plt.show()

# Assuming 'graph' is already created and 'nodes' GeoDataFrame is available
fig, ax = ox.plot_graph(graph, show=False, close=False)

# Plotting stations
for node in potential_station_nodes:
    x, y = nodes.loc[node, 'x'], nodes.loc[node, 'y']
    ax.scatter(x, y, c='red', s=100, label='Station')

# Plotting a single trip for demonstration
origin_node, destination_node = trip_pairs[0][0], trip_pairs[2][1]  # Example trip
route = ox.shortest_path(graph, origin_node, destination_node)
ox.plot_graph_route(graph, route, route_color='blue', route_linewidth=4, ax=ax, close=False)

plt.show()

import pandas as pd

# Assuming your existing variables are available here

# Create DataFrame for stations
stations_data = {
    "Node": potential_station_nodes,
    "Charging Slots": [charging_slots[node] for node in potential_station_nodes]
}
stations_df = pd.DataFrame(stations_data)


def generate_trips(scenario):
    # Adjust the number of trips based on the scenario
    if scenario == 'Weekday':
        num_trips = 30
        demand_probability_range = 0.4
    elif scenario == 'Saturday':
        num_trips = 30
        demand_probability_range = 0.35
    else:  # Assuming 'Sunday' as the "normal" scenario
        num_trips = 30
        demand_probability_range = 0.25


    trip_data = []
    for _ in range(num_trips):
        station1, station2 = random.sample(potential_station_nodes, 2)
        start_time = start_time_range + timedelta(minutes=random.randint(0, int(Tmax.total_seconds() / 60) - 1))
        route = ox.shortest_path(graph, station1, station2)

        if route:
            route_length_meters = sum(ox.utils_graph.get_route_edge_attributes(graph, route, 'length'))
            route_length_km = route_length_meters / 1000
            battery_consumption = battery_consumption_rate * route_length_km
            travel_duration = calculate_travel_time(route_length_meters, average_speed_kmh)
            travel_time_minutes = travel_duration.total_seconds() / 60
            trip_profit = profit_per_minute * travel_time_minutes,
            demand_probability = demand_probability_range

            trip_data.append({
                'Scenario': scenario,
                'Demand Probability': demand_probability,
                'Origin Node': station1,
                'Destination Node': station2,
                'Start Time': start_time,
                'End Time': start_time + travel_duration,
                'Route Length (km)': route_length_km,
                'Battery Consumption (kWh)': battery_consumption,
                'Profit Contribution (IDR)': trip_profit
            })

    return pd.DataFrame(trip_data)

# Generate trips for each scenario
df_high_demand = generate_trips('Weekday')
df_low_demand = generate_trips('Saturday')
df_normal_demand = generate_trips('Sunday')

# Combine all scenarios into a single DataFrame
df_all_scenarios = pd.concat([df_high_demand, df_low_demand, df_normal_demand])

# Save the datasets as CSV files
stations_df.to_csv('stations_data.csv', index=False)
df_all_scenarios.to_csv('trips_data.csv', index=False)

