# -*- coding: utf-8 -*-
"""Copy of bismillah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QGAjGk3z301I7KFNspiDdZrCo1jN0wYL
"""

!pip install gurobipy

import random
from gurobipy import Model, GRB, Env
import pandas as pd

# Load your data here
trips_data = pd.read_csv('trips_data (lama) - Copy.csv')
stations_data = pd.read_csv('stations_data.csv')

# Parameters
num_scenarios = trips_data['Scenario'].nunique()
num_trips = len(trips_data)
num_stations = len(stations_data)
budget = 40000  # Adjust as necessary
num_cars = 30 # Adjust as necessary
car_cost_per_car = 2000  # Adjust as necessary
car_costs = [car_cost_per_car] * num_cars

# Extracting data from the datasets
trip_profits = trips_data['Profit Contribution (IDR)'].tolist()
station_costs = [5000] * num_stations  # Assuming a fixed cost for each station
station_capacity = stations_data['Charging Slots'].tolist()

# Create a mapping from Node IDs to station indices
node_to_station_index = {node: index for index, node in enumerate(stations_data['Node'])}

# Assuming 'Scenario' is a column with scenario names, replace it with numerical indices
scenario_index_mapping = {name: index for index, name in enumerate(trips_data['Scenario'].unique())}
trips_data['Scenario_Index'] = trips_data['Scenario'].map(scenario_index_mapping)

# Redefine trips_info using numerical indices
trips_info = {(i, scenario_index_mapping[row['Scenario']]): (node_to_station_index[row['Origin Node']], node_to_station_index[row['Destination Node']])
              for i, row in trips_data.iterrows()}

demand_probabilities = trips_data.groupby('Scenario')['Demand Probability'].mean().tolist()

demand_probabilities

trips_info

from gurobipy import Model, GRB, Env
import pandas as pd

# Assuming data loading and preprocessing is done here
# trips_data, stations_data, num_scenarios, num_trips, num_stations, budget, num_cars, car_costs, trip_profits, station_costs, station_capacity, trips_info

params = {
    "WLSACCESSID": 'a3e4f680-0ee5-4ec5-9367-5da9805d3765',
    "WLSSECRET": '3594c622-c8c4-4418-8f99-1f49cc688f56',
    "LICENSEID": 2452657,
}
env = Env(params=params)

m = Model("Time-Dependent Integer Linear Program", env=env)

# Decision variables for trips, stations, and cars
x = m.addVars(num_scenarios, num_trips, vtype=GRB.BINARY, name="x")
y = m.addVars(num_stations, vtype=GRB.BINARY, name="y")
z = m.addVars(num_cars, vtype=GRB.BINARY, name="z")
# car_assignment = m.addVars(num_cars, num_trips, vtype=GRB.BINARY, name="car_assignment")
car_assignment = m.addVars([(h, t) for h in range(num_cars) for t, scenario in trips_info.keys()], vtype=GRB.BINARY, name="car_assignment")
recharged = m.addVars(num_cars, vtype=GRB.BINARY, name="recharged")

# Objective
m.setObjective(
    sum(demand_probabilities[o] * x[o, t] * trip_profits[t] for t in range(num_trips) for o in range(num_scenarios)) -
    sum(y[s] * station_costs[s] for s in range(num_stations)) -
    sum(z[h] * car_costs[h] for h in range(num_cars)),
    GRB.MAXIMIZE
)

# Budget constraint
m.addConstr(
    sum(y[s] * station_costs[s] for s in range(num_stations)) +
    sum(z[h] * car_costs[h] for h in range(num_cars)) <= budget,
    "Budget"
)

# Station capacity constraints
for s in range(num_stations):
    m.addConstr(
        sum(x[scenario, trip_index] for trip_index, scenario in trips_info.keys()
            if trips_info[trip_index, scenario][0] == s or trips_info[trip_index, scenario][1] == s) <= station_capacity[s],
        f"Capacity_station_{s}"
    )

# Car assignment constraints based on station build decisions
for h in range(num_cars):
    for t, scenario_index in trips_info.keys():
        start_station, end_station = trips_info[(t, scenario_index)]
        m.addConstr(car_assignment[h, t] <= y[start_station], f"Car_assignment_start_{h}_{t}_{scenario_index}")
        m.addConstr(car_assignment[h, t] <= y[end_station], f"Car_assignment_end_{h}_{t}_{scenario_index}")

# Flow conservation constraints
for s in range(num_stations):
    m.addConstr(
        sum(car_assignment[h, t] for h in range(num_cars) for t, scenario in trips_info.keys() if trips_info[t, scenario][1] == s) ==
        sum(car_assignment[h, t] for h in range(num_cars) for t, scenario in trips_info.keys() if trips_info[t, scenario][0] == s),
        f"Flow_conservation_station_{s}"
    )

# Recharge before use constraints
for h in range(num_cars):
    m.addConstr(recharged[h] >= z[h], f"Recharge_before_use_{h}")

# Ensure car is purchased if it is assigned to any trip
for h in range(num_cars):
    for t, scenario in trips_info.keys():
        m.addConstr(z[h] >= car_assignment[h, t], f"Ensure_purchase_if_assigned_{h}_{t}_{scenario}")

# Adjusted constraint for trip assignment to ensure scenario-specific assignments
for t in range(num_trips):
    for o in range(num_scenarios):
        m.addConstr(
            sum(car_assignment[h, t] for h in range(num_cars) if trips_data.loc[t, 'Scenario_Index'] == o) >= x[o, t],
            f"Trip_{t}_assigned_car_scenario_{o}"
        )

# Optimize the model
m.optimize()

# Print the solution
if m.status == GRB.OPTIMAL:
    print('Optimal solution found:')
    built_stations = [s for s in range(num_stations) if y[s].x > 0.5]
    print("Stations Built:", built_stations)

    for o in range(num_scenarios):
        accepted_trips = [t for t in range(num_trips) if x[o, t].x > 0.5]
        print(f"Trips accepted in scenario {o}:", accepted_trips)
else:
    print('No optimal solution found.')

m.objVal

z

recharged

car_assignment

