# -*- coding: utf-8 -*-
"""fork_of_skripsi_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qzJXWbgeGK040cSKp-AqNA52LqEJVZ2
"""

import pandas as pd
import numpy as np
import random
from geopy.distance import geodesic
import folium
import pickle
import matplotlib.pyplot as plt
import math

# Load data
stations_df = pd.read_csv('/kaggle/input/skripsi-generating-data/stations_data.csv')
scenarios_df = pd.read_csv('/kaggle/input/skripsi-generating-data/scenarios_data.csv')
distance_matrix = pd.read_csv('/kaggle/input/skripsi-generating-data/distance_matrix.csv', index_col=0)

with open('/kaggle/input/skripsi-generating-data/other_data.pkl', 'rb') as f:
    other_data = pickle.load(f)

num_stations = other_data['num_stations']
num_scenarios = other_data['num_scenarios']
max_trips = max(scenarios_df.groupby('scenario').size())
Tmax = other_data['Tmax']
budget_fraction = other_data['budget_fraction']

scenarios_df['origin'] = scenarios_df['origin'].apply(eval)
scenarios_df['destination'] = scenarios_df['destination'].apply(eval)

scenario_probabilities = {
    0: 0.30,  # Weekdays
    1: 0.34,  # Saturday
    2: 0.36   # Sunday
}

def calculate_distance(coord1, coord2):
    return geodesic(coord1, coord2).kilometers

class BikeShareFHO:
    def __init__(self, stations_df, scenarios_df, distance_matrix, num_stations, num_scenarios, max_trips, Tmax, budget_fraction, pop_size, max_generations, other_data):
        self.stations_df = stations_df
        self.scenarios_df = scenarios_df
        self.distance_matrix = distance_matrix
        self.num_stations = num_stations
        self.num_scenarios = num_scenarios
        self.max_trips = max_trips
        self.Tmax = Tmax
        self.budget_fraction = budget_fraction
        self.pop_size = pop_size
        self.max_generations = max_generations
        self.scenario_probabilities = scenario_probabilities
        self.bike_cost = 4000000

        self.charging_time = other_data['charging_time']
        self.max_trip_duration = other_data['max_trip_duration']
        self.max_battery_distance = other_data['max_battery_distance']

        self.charging_rate = 1 / self.charging_time

        self.charging_status = np.zeros((num_scenarios, 75, Tmax))

        self.n_dims = num_stations + 75 + num_scenarios * max_trips
        self.Pop = np.random.randint(0, 2, (pop_size, self.n_dims))
        for solution in self.Pop:
            if sum(solution[:self.num_stations]) == 0:
                solution[np.random.randint(0, self.num_stations)] = 1
        self.best_costs = []
        self.costs_iter = []
        self.best_solution = None
        self.path = []

    def calculate_distance(self, coord1, coord2):
        return geodesic(coord1, coord2).kilometers

    def objective_function(self, solution):
        y = solution[:self.num_stations]
        b = solution[self.num_stations:self.num_stations+75]
        x = solution[self.num_stations+75:].reshape(self.num_scenarios, self.max_trips)

        # Calculate expected profit
        expected_profit = 0
        for sc in range(self.num_scenarios):
            scenario_prob = scenario_probabilities[sc]  # Use the defined probabilities
            scenario_trips = self.scenarios_df[self.scenarios_df['scenario'] == sc]
            num_trips_in_scenario = len(scenario_trips)
            scenario_profit = sum(scenario_trips['profit'].iloc[:min(num_trips_in_scenario, self.max_trips)] *
                                  x[sc, :min(num_trips_in_scenario, self.max_trips)])
            expected_profit += scenario_prob * scenario_profit

        # Calculate costs
        station_costs = np.dot(self.stations_df['opening_cost'], y)
        bike_costs = self.bike_cost * np.sum(b)

        # Calculate net profit
        net_profit = expected_profit - station_costs - bike_costs

        # Check constraints
        if not self.constraints(solution):
            return 0  # Return 0 if constraints are violated

        return max(0, net_profit)  # Ensure non-negative return value

    def constraints(self, solution):
        y = solution[:self.num_stations]
        b = solution[self.num_stations:self.num_stations+75]
        x = solution[self.num_stations+75:].reshape(self.num_scenarios, self.max_trips)

        # Budget constraint
        total_cost = np.dot(self.stations_df['opening_cost'], y) + self.bike_cost * np.sum(b)
        budget = self.budget_fraction * (np.sum(self.stations_df['opening_cost']) + self.bike_cost * 75)
        if total_cost > budget:
            return False

        total_bikes = np.sum(b)

        for sc in range(self.num_scenarios):
            scenario_trips = self.scenarios_df[self.scenarios_df['scenario'] == sc]
            num_trips_in_scenario = len(scenario_trips)
            battery_levels = np.ones(75)

            for t in range(self.Tmax):
                # Check trips starting at this time
                starting_trips = scenario_trips[scenario_trips['start_time'] == t]
                for idx, trip in starting_trips.iterrows():
                    if idx < self.max_trips and x[sc, idx] == 1:  # If this trip is accepted and within max_trips
                        available_bikes = np.where((b == 1) & (battery_levels >= trip['battery_consumption']))[0]
                        if len(available_bikes) == 0:
                            return False  # No bike available with sufficient charge
                        chosen_bike = available_bikes[0]
                        battery_levels[chosen_bike] -= trip['battery_consumption']

                # Charge bikes
                battery_levels = np.minimum(1, battery_levels + self.charging_rate)

            # Capacity constraint
            for st in range(self.num_stations):
                station_usage = np.sum(x[sc, scenario_trips['origin'] == st]) + np.sum(x[sc, scenario_trips['destination'] == st])
                if station_usage > self.stations_df.loc[st, 'capacity'] * y[st]:
                    return False

            # Vehicle allocation constraint
            if np.sum(x[sc]) > total_bikes:
                return False

            # Trip allocation constraint
            if np.any(x[sc] > 1):
                return False

            # Flow conservation constraint
            for st in range(self.num_stations):
                incoming_flow = np.sum(x[sc, scenario_trips['destination'] == st])
                outgoing_flow = np.sum(x[sc, scenario_trips['origin'] == st])
                if incoming_flow != outgoing_flow:
                    return False

            # Time-dependent constraint
            for t in range(self.Tmax):
                bikes_in_use = np.sum(x[sc, (scenario_trips['start_time'] <= t) & (scenario_trips['end_time'] > t)])
                if bikes_in_use > total_bikes:
                    return False

            # Rebalancing constraint (simplified)
            max_imbalance = 0.2 * total_bikes
            for st in range(self.num_stations):
                net_flow = np.sum(x[sc, scenario_trips['destination'] == st]) - np.sum(x[sc, scenario_trips['origin'] == st])
                if abs(net_flow) > max_imbalance:
                    return False

        # New constraint: Build unaccepted stations if no station within radius
        radius = 1
        stations_coords = self.stations_df[['latitude', 'longitude']].values

        # Calculate distances using Haversine formula
        lat1, lon1 = np.radians(stations_coords[:, 0])[:, np.newaxis], np.radians(stations_coords[:, 1])[:, np.newaxis]
        lat2, lon2 = np.radians(stations_coords[:, 0]), np.radians(stations_coords[:, 1])
        dlat, dlon = lat2 - lat1, lon2 - lon1
        a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
        distances = 2 * 6371 * np.arcsin(np.sqrt(a))  # 6371 is Earth's radius in km

        for st in range(self.num_stations):
            if y[st] == 0:  # If station is not built
                if not np.any((distances[st] <= radius) & (y == 1)):
                    y[st] = 1  # Build the station

        # Recalculate budget constraint after potential new stations
        if np.dot(self.stations_df['opening_cost'], y) + 50000 * np.sum(b) > budget:
            return False

        return True

    def territories(self, Fire_Hawks, Preys):
        territories = {i: np.array([]) for i in range(len(Fire_Hawks))}
        preys_left = Preys.copy()
        for i in range(len(Fire_Hawks)):
            D = np.linalg.norm(Fire_Hawks[i] - preys_left, axis=1)
            sorted_preys_idx = np.argsort(D)
            alpha = np.random.randint(1, len(preys_left)) if len(preys_left) > 1 else 1
            my_preys = sorted_preys_idx[:alpha]
            territories[i] = preys_left[my_preys]
            preys_left = preys_left[sorted_preys_idx[alpha:]]
            if len(preys_left) == 0:
                break
        if len(preys_left) > 0:
            territories[len(Fire_Hawks)-1] = np.concatenate((territories[len(Fire_Hawks)-1], preys_left))
        return territories

    def maximize_FHO(self):
        print("Starting Fire Hawk Optimizer")
        Pop = self.Pop
        pop_size = self.pop_size
        max_generations = self.max_generations

        print(f"Evaluating initial population of size {pop_size}")
        cost = np.array([self.objective_function(Pop[i]) for i in range(pop_size)])

        print("Ordering candidates")
        Pop = Pop[np.argsort(cost)[::-1]]
        cost = np.sort(cost)[::-1]
        SP = Pop.mean(axis=0)

        num_hawks_history = []
        num_prey_history = []

        GB = cost[0]
        Best_Hawk = Pop[0]
        self.path.append(Best_Hawk)
        print(f"Initial best solution: {GB}")

        FEs = pop_size

        # Convergence parameters
        convergence_threshold = 1
        patience = 50
        min_iterations = 50
        no_improvement_counter = 0
        best_cost_history = [GB]

        print(f"Starting main loop for up to {max_generations} generations")
        for generation in range(max_generations):
            print(f"\nGeneration {generation + 1}")

            num_Hawks = np.random.randint(1, int(pop_size/5)+1)
            num_Prey = pop_size - num_Hawks

            print(f"Number of Fire Hawks: {num_Hawks}, Number of Prey: {num_Prey}")
            num_hawks_history.append(num_Hawks)
            num_prey_history.append(num_Prey)

            Fire_Hawks = Pop[:num_Hawks]
            Preys = Pop[num_Hawks:]

            print("Getting territories")
            territories = self.territories(Fire_Hawks, Preys)

            Pop_Tot = []
            cost = []

            print("Moving Fire Hawks and Preys")
            for i in territories:
                PR = territories[i].copy()
                FHl = Fire_Hawks[i].copy()
                SPl = PR.mean(axis=0) if len(territories[i]) > 0 else np.zeros(FHl.shape)
                a, b = np.random.uniform(0, 1, size=2)
                FHnear = Fire_Hawks[np.random.randint(num_Hawks)]
                FHl_new = FHl + (a * GB - b * FHnear)
                FHl_new = np.clip(FHl_new, 0, 1)
                Pop_Tot.append(FHl_new)

                for q in range(len(PR)):
                    a, b = np.random.uniform(0, 1, size=2)
                    PRq_new1 = PR[q].copy() + ((a * FHl - b * SPl))
                    PRq_new1 = np.clip(PRq_new1, 0, 1)
                    Pop_Tot.append(PRq_new1)

                    a, b = np.random.uniform(0, 1, size=2)
                    FHAlter = Fire_Hawks[np.random.randint(num_Hawks)]
                    PRq_new2 = PR[q].copy() + ((a * FHAlter - b * SP))
                    PRq_new2 = np.clip(PRq_new2, 0, 1)
                    Pop_Tot.append(PRq_new2)

            print("Converting to binary and evaluating cost")
            Pop_Tot = np.round(np.array(Pop_Tot)).astype(int)
            for i in range(len(Pop_Tot)):
                cost.append(self.objective_function(Pop_Tot[i]))
                FEs += 1

            print("Creating new population")
            order_idx = np.argsort(cost)[::-1]
            cost = np.sort(cost)[::-1]
            Pop_Tot = Pop_Tot[order_idx]

            # Ensure population size remains constant
            Pop = Pop_Tot[:pop_size]
            cost = cost[:pop_size]

            print(f"Current best solution: {cost[0]}")
            if cost[0] > GB:
                Best_Position = Pop[0]
                GB = cost[0]
                self.best_costs.append(GB)
                self.best_solution = Pop[0]
                self.path.append(Best_Position)
                print(f"New best solution found: {GB}")
                no_improvement_counter = 0
            else:
                self.best_costs.append(GB)
                no_improvement_counter += 1

            self.costs_iter.append(cost[0])
            best_cost_history.append(GB)

            # Check for convergence
            if generation >= min_iterations:
                relative_improvement = (best_cost_history[-1] - best_cost_history[-patience-1]) / best_cost_history[-patience-1]
                if relative_improvement < convergence_threshold:
                    print(f"Converged after {generation + 1} generations")
                    break

            if no_improvement_counter >= patience:
                print(f"No improvement for {patience} generations. Stopping.")
                break

        print("\nOptimization completed")
        print(f"Best solution found: {GB}")

        self.num_hawks_history = num_hawks_history
        self.num_prey_history = num_prey_history

        return (GB, self.best_solution)

    def plot_results(self):
        plt.figure(figsize=(12, 8))

        # Plot cost over iterations
        plt.subplot(2, 1, 1)
        plt.plot(range(len(self.costs_iter)), self.costs_iter, label='Iteration Objective Function')
        plt.plot(range(len(self.best_costs)), self.best_costs, label='Best Ojective Function')
        plt.title('Objective Function Iterations')
        plt.xlabel('Iteration')
        plt.ylabel('Objective Funcntion')
        plt.legend()

        # Plot number of Fire Hawks and Prey over iterations
        plt.subplot(2, 1, 2)
        plt.plot(range(len(self.num_hawks_history)), self.num_hawks_history, label='Fire Hawks')
        plt.plot(range(len(self.num_prey_history)), self.num_prey_history, label='Prey')
        plt.title('Number of Fire Hawks and Prey over Iterations')
        plt.xlabel('Iteration')
        plt.ylabel('Number')
        plt.legend()

        plt.tight_layout()
        plt.show()

pop_size = 250
max_generations = 100

fho = BikeShareFHO(stations_df, scenarios_df, distance_matrix, num_stations, num_scenarios,
                   max_trips, Tmax, budget_fraction, pop_size, max_generations, other_data)
best_cost, best_solution = fho.maximize_FHO()

# Extract results
y = best_solution[:num_stations]
b = best_solution[num_stations:num_stations+75]
x = best_solution[num_stations+75:].reshape(num_scenarios, max_trips)

print("\nFinal Results:")
print("Optimal station locations:", y)
print("Number of bikes purchased:", sum(b))
print("Expected profit:", best_cost)

# Additional analysis
opened_stations = [i for i in range(num_stations) if y[i] == 1]
print("\nDetailed Analysis:")
print("Opened stations:", opened_stations)
print("Total capacity of opened stations:", sum(stations_df.loc[opened_stations, 'capacity']))
print("Total charging slots of opened stations:", sum(stations_df.loc[opened_stations, 'charging_slots']))

for sc in range(num_scenarios):
    accepted_trips = sum(x[sc])
    total_trips = len(scenarios_df[scenarios_df['scenario'] == sc])
    scenario_name = ["Weekdays", "Saturday", "Sunday"][sc]
    print(f"Scenario {sc} ({scenario_name}, prob: {scenario_probabilities[sc]:.2f}): Accepted trips: {accepted_trips}/{total_trips} ({accepted_trips/total_trips:.2%})")

# Calculate and print the average utilization of bikes
total_trips = sum(sum(x[sc]) for sc in range(num_scenarios))
avg_utilization = total_trips / (sum(b) * num_scenarios)
print(f"\nAverage bike utilization: {avg_utilization:.2%}")

# Plot the results
fho.plot_results()

from folium.plugins import MarkerCluster

# Create a map centered on Yogyakarta
m = folium.Map(location=[-7.7956, 110.3695], zoom_start=13)

# Add markers for built stations
for idx, row in stations_df.iterrows():
    if y[idx] == 1:
        folium.Marker(
            location=[row['latitude'], row['longitude']],
            popup=f"Station {idx}: Capacity {row['capacity']}",
            icon=folium.Icon(color='red', icon='info-sign')
        ).add_to(m)

# Create a MarkerCluster for trip visualization
trip_cluster = MarkerCluster().add_to(m)

# Visualize accepted trips for each scenario
for scenario in range(num_scenarios):
    scenario_trips = scenarios_df[scenarios_df['scenario'] == scenario]
    for trip_id in range(len(scenario_trips)):
        if x[scenario][trip_id] == 1:
            trip = scenario_trips.iloc[trip_id]
            origin = trip['origin']
            destination = trip['destination']

            # Draw a line for the trip
            folium.PolyLine(
                locations=[origin, destination],
                color="blue",
                weight=2,
                opacity=0.8
            ).add_to(trip_cluster)

            # Add markers for origin and destination
            folium.Marker(
                location=origin,
                popup=f"Origin: Trip {trip_id}, Scenario {scenario}",
                icon=folium.Icon(color='green', icon='play')
            ).add_to(trip_cluster)

            folium.Marker(
                location=destination,
                popup=f"Destination: Trip {trip_id}, Scenario {scenario}",
                icon=folium.Icon(color='orange', icon='stop')
            ).add_to(trip_cluster)

# Save the map
m.save("bike_sharing_optimization_results.html")

print("Map with optimization results has been saved as 'bike_sharing_optimization_results.html'")

# Print accepted trips for each scenario
for scenario in range(num_scenarios):
    print(f"\nAccepted trips for Scenario {scenario}:")
    scenario_trips = scenarios_df[scenarios_df['scenario'] == scenario]
    for trip_id in range(len(scenario_trips)):
        if x[scenario][trip_id] == 1:
            trip = scenario_trips.iloc[trip_id]
            print(f"Trip {trip_id}: From {trip['origin']} to {trip['destination']}, "
                  f"Start time: {trip['start_time']}, End time: {trip['end_time']}, "
                  f"Profit: {trip['profit']}")