# -*- coding: utf-8 -*-
"""skripsi_generating_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9f1G6_zx_vka3b8XYzsEm-HgW7NBfC8
"""

import pandas as pd
import random
import numpy as np
from geopy.distance import geodesic
import folium
import matplotlib.pyplot as plt
import pickle

# Parameters
num_stations_options = [15]
capacity_min = 5
capacity_max = 10
alpha_min, alpha_max = 10000000, 50000000
beta_min, beta_max = 2000000, 5000000
num_scenarios_options = [3]
trips_per_scenario_options = [30]
Tmax_options = [15]
max_walking_time = 10
budget_fraction = 0.8

# Tugu Yogyakarta as the center
tugu_yogyakarta = (-7.7829, 110.3671)

strategic_locations = [
    (-7.7891, 110.3614),  # Yogyakarta Tugu Train Station
    (-7.7931, 110.3656),  # Malioboro Mall
    (-7.7824, 110.3750),  # Beringharjo Market
    (-7.7830, 110.3657),  # Bank Indonesia Yogyakarta
    (-7.7801, 110.3712),  # Yogyakarta Palace
    (-7.7764, 110.3632),  # UGM (Universitas Gadjah Mada)
]

# Scenario probabilities
scenario_probabilities = {
    0: 0.30,  # Weekdays
    1: 0.34,  # Saturday
    2: 0.36   # Sunday
}

def generate_random_coordinates(center, num_points, radius=0.05, min_distance=1.0):
    coords = []
    while len(coords) < num_points:
        lat = center[0] + random.uniform(-radius, radius)
        long = center[1] + random.uniform(-radius, radius)
        new_coord = (lat, long)

        if all(geodesic(new_coord, existing_coord).kilometers >= min_distance for existing_coord in coords + strategic_locations):
            coords.append(new_coord)

    return [coord[0] for coord in coords], [coord[1] for coord in coords]

num_stations = random.choice(num_stations_options)
num_random_stations = num_stations - len(strategic_locations)
random_lats, random_longs = generate_random_coordinates(tugu_yogyakarta, num_random_stations)
combined_lats = [loc[0] for loc in strategic_locations] + random_lats
combined_longs = [loc[1] for loc in strategic_locations] + random_longs

CHARGING_TIME = 2  # hours
MAX_TRIP_DURATION = 3  # hours
MAX_BATTERY_DISTANCE = 50  # km

# Modify station generation
stations_data = []
for i in range(num_stations):
    capacity = random.randint(capacity_min, capacity_max)
    alpha = random.randint(alpha_min, alpha_max)
    beta = random.randint(beta_min, beta_max)
    opening_cost = alpha + beta * capacity
    min_bikes = max(1, int(capacity * 0.2))
    max_bikes = int(capacity * 0.8)
    charging_slots = random.randint(1, min(5, capacity))
    stations_data.append((i, capacity, opening_cost, combined_lats[i], combined_longs[i], min_bikes, max_bikes, charging_slots))

stations_df = pd.DataFrame(stations_data, columns=['station_id', 'capacity', 'opening_cost', 'latitude', 'longitude', 'min_bikes', 'max_bikes', 'charging_slots'])

# Constants
WALKING_DISTANCE_THRESHOLD = 0.5

# Generate Scenarios
num_scenarios = random.choice(num_scenarios_options)
Tmax = random.choice(Tmax_options)

# Function to calculate trip distance
def calculate_trip_distance(origin, destination):
    return geodesic(origin, destination).kilometers

# Modify scenario generation
def generate_initial_scenarios(num_scenarios, num_trips_options, stations_df, Tmax, scenario_probabilities):
    scenarios_data = []
    for scenario in range(num_scenarios):
        num_trips = random.choice(num_trips_options)
        for trip_id in range(num_trips):
            while True:
                origin_station = stations_df.sample(n=1).iloc[0]
                dest_station = stations_df.sample(n=1).iloc[0]

                origin_lat = origin_station['latitude'] + random.uniform(-0.006, 0.006)
                origin_long = origin_station['longitude'] + random.uniform(-0.006, 0.006)
                dest_lat = dest_station['latitude'] + random.uniform(-0.006, 0.006)
                dest_long = dest_station['longitude'] + random.uniform(-0.006, 0.006)

                origin = (origin_lat, origin_long)
                destination = (dest_lat, dest_long)

                trip_distance = calculate_trip_distance(origin, destination)

                if origin != destination and trip_distance <= MAX_BATTERY_DISTANCE:
                    sk = random.randint(0, Tmax - MAX_TRIP_DURATION - 1)
                    ek = random.randint(sk + 1, min(Tmax, sk + MAX_TRIP_DURATION))
                    trip_duration = ek - sk

                    if ek <= Tmax:
                        profit = 10000000 * trip_duration
                        battery_consumption = trip_distance / MAX_BATTERY_DISTANCE
                        probability = scenario_probabilities[scenario]
                        scenarios_data.append((scenario, trip_id, origin, destination, sk, ek, profit, trip_distance, battery_consumption, probability))  # Add probability here
                        break

    return scenarios_data

scenarios_data = generate_initial_scenarios(num_scenarios, trips_per_scenario_options, stations_df, Tmax, scenario_probabilities)
scenarios_df = pd.DataFrame(scenarios_data, columns=['scenario', 'trip_id', 'origin', 'destination', 'start_time', 'end_time', 'profit', 'distance', 'battery_consumption', 'probability'])

def calculate_walking_time(coord1, coord2):
    distance_km = geodesic(coord1, coord2).kilometers
    walking_speed_kmph = 5
    walking_time_min = (distance_km / walking_speed_kmph) * 60
    return walking_time_min

distance_matrix = pd.DataFrame(index=stations_df['station_id'], columns=stations_df['station_id'])
for i in stations_df['station_id']:
    for j in stations_df['station_id']:
        if i != j:
            distance = calculate_trip_distance(
                (stations_df.loc[i, 'latitude'], stations_df.loc[i, 'longitude']),
                (stations_df.loc[j, 'latitude'], stations_df.loc[j, 'longitude'])
            )
            distance_matrix.loc[i, j] = distance
        else:
            distance_matrix.loc[i, j] = 0

def create_potential_stations_and_trips_map(stations_df, scenarios_df):
    m = folium.Map(location=[tugu_yogyakarta[0], tugu_yogyakarta[1]], zoom_start=14)

    # Add station markers
    for idx, row in stations_df.iterrows():
        folium.Marker(
            location=[row['latitude'], row['longitude']],
            popup=f"Station ID: {row['station_id']}, Capacity: {row['capacity']}, Opening Cost: IDR {row['opening_cost']:,}",
            icon=folium.Icon(color='blue', icon='info-sign')
        ).add_to(m)

    # Add trip lines
    for _, trip in scenarios_df.iterrows():
        folium.PolyLine(
            locations=[trip['origin'], trip['destination']],
            color="red",
            weight=2,
            opacity=0.8,
            popup=f"Scenario: {trip['scenario']}, Trip ID: {trip['trip_id']}"
        ).add_to(m)

    return m

# Save the data
stations_df.to_csv('stations_data.csv', index=False)
scenarios_df.to_csv('scenarios_data.csv', index=False)
distance_matrix.to_csv('distance_matrix.csv')

with open('other_data.pkl', 'wb') as f:
    pickle.dump({
        'num_stations': num_stations,
        'num_scenarios': num_scenarios,
        'max_trips': max(scenarios_df.groupby('scenario')['trip_id'].count()),
        'Tmax': Tmax,
        'budget_fraction': budget_fraction,
        'charging_time': CHARGING_TIME,
        'max_trip_duration': MAX_TRIP_DURATION,
        'max_battery_distance': MAX_BATTERY_DISTANCE,
        'scenario_probabilities': scenario_probabilities
    }, f)

potential_stations_and_trips_map = create_potential_stations_and_trips_map(stations_df, scenarios_df)

potential_stations_and_trips_map.save("potential_stations_and_trips_map.html")

potential_stations_and_trips_map