# -*- coding: utf-8 -*-
"""skripsi-example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DrLktDF7SXFcqLXMuWfJjyW4s6X6p9r
"""

import numpy as np
import random
import matplotlib.pyplot as plt

class SimpleFHO:
    def __init__(self, pop_size, max_generations):
        self.pop_size = pop_size
        self.max_generations = max_generations
        self.best_solution = self.initialize_solution()  # Initialize with a valid solution
        self.best_fitness = float('-inf')
        self.fitness_history = []

    def initialize_solution(self):
        while True:
            solution = np.zeros(10, dtype=int)
            solution[:2] = np.random.randint(0, 4, size=2)  # x1 and x2
            solution[2:6] = np.random.randint(0, 2, size=4)  # w variables
            solution[6:] = np.random.randint(0, 4, size=4)  # z variables
            if self.constraints(solution):
                return solution

    def objective_function(self, solution):
        _, _, _, _, _, _, z11, z12, z21, z22 = solution
        return 0.7 * (z11 + z21) + 0.3 * (z12 + z22)

    def constraints(self, solution):
        x1, x2, w11, w12, w21, w22, z11, z12, z21, z22 = solution

        if x1 + x2 != 3:
            return False
        if x1 + w11 < z11 or x2 + w12 < z12:
            return False
        if w11 + w12 != 1:
            return False
        if z11 > 3 or z12 > 1:
            return False
        if x1 + w21 < z21 or x2 + w22 < z22:
            return False
        if w21 + w22 != 1:
            return False
        if z21 > 1 or z22 > 3:
            return False
        if any(v < 0 for v in solution):
            return False

        return True

    def territories(self, Fire_Hawks, Preys):
        territories = {i: np.array([]) for i in range(len(Fire_Hawks))}
        preys_left = Preys.copy()
        for i in range(len(Fire_Hawks)):
            D = np.linalg.norm(Fire_Hawks[i] - preys_left, axis=1)
            sorted_preys_idx = np.argsort(D)
            alpha = np.random.randint(1, len(preys_left)) if len(preys_left) > 1 else 1
            my_preys = sorted_preys_idx[:alpha]
            territories[i] = preys_left[my_preys]
            preys_left = preys_left[sorted_preys_idx[alpha:]]
            if len(preys_left) == 0:
                break
        if len(preys_left) > 0:
            territories[len(Fire_Hawks)-1] = np.concatenate((territories[len(Fire_Hawks)-1], preys_left))
        return territories


    def optimize(self):
        print("Initializing population...")
        Pop = np.array([self.initialize_solution() for _ in range(self.pop_size)])
        fitness = np.array([self.objective_function(sol) for sol in Pop])

        print(f"Initial population size: {len(Pop)}")
        print(f"Sample solution: {Pop[0]}")
        print(f"Sample fitness: {fitness[0]}")

        best_idx = np.argmax(fitness)
        self.best_solution = Pop[best_idx]
        self.best_fitness = fitness[best_idx]
        print(f"Initial best solution: {self.best_solution}")
        print(f"Initial best fitness: {self.best_fitness}")

        for generation in range(self.max_generations):
            print(f"\nGeneration {generation+1}")

            num_Hawks = np.random.randint(1, int(self.pop_size/5)+1)
            print(f"Number of Fire Hawks: {num_Hawks}")

            # Select fire hawks and preys
            Fire_Hawks = Pop[np.argsort(fitness)[-num_Hawks:]]
            Preys = Pop[np.argsort(fitness)[:-num_Hawks]]

            print("Fire Hawks:")
            print(Fire_Hawks)
            print("Preys:")
            print(Preys)

            # Print the equation for X
            print("\nEquation for X:")
            print("X = [")
            for i in range(len(Pop)):
                print(f"  {Pop[i]}")
            print("]")

            territories = self.territories(Fire_Hawks, Preys)
            print(f"\nNumber of territories: {len(territories)}")

            new_Pop = []
            for i in territories:
                FHl = Fire_Hawks[i]
                PR = territories[i]
                SPl = PR.mean(axis=0) if len(PR) > 0 else np.zeros(FHl.shape)

                print(f"\nTerritory {i+1}:")
                print(f"Fire Hawk (FH_{i+1}): {FHl}")
                print(f"Number of Preys: {len(PR)}")
                print(f"Safe Place (SP_{i+1}): {SPl}")

                # Print distances
                print("\nDistances:")
                for k, prey in enumerate(PR):
                    D = np.linalg.norm(FHl - prey)
                    print(f"D_{k+1}_{i+1} = {D}")

                # Fire Hawk movement
                a, b = np.random.uniform(0, 1, size=2)
                FHnear = Fire_Hawks[np.random.randint(num_Hawks)]
                FHl_new = FHl + (a * self.best_solution - b * FHnear)
                FHl_new = np.round(np.clip(FHl_new, 0, 3)).astype(int)
                if self.constraints(FHl_new):
                    new_Pop.append(FHl_new)
                    print(f"\nUpdated Fire Hawk (FH_{i+1}^new): {FHl_new}")
                    print(f"FH_{i+1}^new = FH_{i+1} + ({a:.2f} * GB - {b:.2f} * FH_near)")
                    print(f"Where GB = {self.best_solution} and FH_near = {FHnear}")

                # Prey movements (showing only the first prey for brevity)
                if len(PR) > 0:
                    PRq = PR[0]
                    a, b = np.random.uniform(0, 1, size=2)
                    PRq_new1 = PRq + (a * FHl - b * SPl)
                    PRq_new1 = np.round(np.clip(PRq_new1, 0, 3)).astype(int)
                    if self.constraints(PRq_new1):
                        new_Pop.append(PRq_new1)
                        print(f"\nUpdated Prey (PR_1^new, inside territory): {PRq_new1}")
                        print(f"PR_1^new = PR_1 + ({a:.2f} * FH_{i+1} - {b:.2f} * SP_{i+1})")
                        print(f"Where PR_1 = {PRq}, FH_{i+1} = {FHl}, and SP_{i+1} = {SPl}")

                    a, b = np.random.uniform(0, 1, size=2)
                    FHAlter = Fire_Hawks[np.random.randint(num_Hawks)]
                    SP = Pop.mean(axis=0)
                    PRq_new2 = PRq + (a * FHAlter - b * SP)
                    PRq_new2 = np.round(np.clip(PRq_new2, 0, 3)).astype(int)
                    if self.constraints(PRq_new2):
                        new_Pop.append(PRq_new2)
                        print(f"\nUpdated Prey (PR_1^new, outside territory): {PRq_new2}")
                        print(f"PR_1^new = PR_1 + ({a:.2f} * FH_Alter - {b:.2f} * SP)")
                        print(f"Where PR_1 = {PRq}, FH_Alter = {FHAlter}, and SP = {SP}")

            # Ensure population size remains constant
            while len(new_Pop) < self.pop_size:
                new_Pop.append(self.initialize_solution())
            new_Pop = new_Pop[:self.pop_size]

            Pop = np.array(new_Pop)
            fitness = np.array([self.objective_function(sol) for sol in Pop])

            best_idx = np.argmax(fitness)
            if fitness[best_idx] > self.best_fitness:
                self.best_solution = Pop[best_idx]
                self.best_fitness = fitness[best_idx]
                print(f"New best solution found: {self.best_solution}")
                print(f"New best fitness: {self.best_fitness}")

            self.fitness_history.append(self.best_fitness)

        print("\nOptimization completed!")
        return self.best_solution, self.best_fitness

    def plot_results(self):
        plt.figure(figsize=(10, 6))
        plt.plot(range(1, len(self.fitness_history) + 1), self.fitness_history)
        plt.title('Best Fitness over Generations')
        plt.xlabel('Generation')
        plt.ylabel('Fitness')
        plt.grid(True)
        plt.show()

# Usage
fho = SimpleFHO(pop_size=10, max_generations=100)
best_solution, best_fitness = fho.optimize()
print(f"Best Solution: {best_solution}")
print(f"Best Fitness: {best_fitness}")
fho.plot_results()